config/routes.rb
SesusoEms::Application.routes.draw do
  #resources :categories
  #resources :order_items
  #resources :products
  #resources :orders
  #resources :customers

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => 'home#index'

  #get ':controller/:action'

  # Order Ticket Workflow
  get 'order_tickets_workflow/start', to: 'order_tickets_workflow#start'
  get 'order_tickets_workflow/select_table', to: 'order_tickets_workflow#select_table'
  get 'order_tickets_workflow/get_ball_tables', to: 'order_tickets_workflow#get_ball_tables'
  get 'order_tickets_workflow/receive_selected_table', to: 'order_tickets_workflow#receive_selected_table'
  get 'order_tickets_workflow/select_amount_of_seats', to: 'order_tickets_workflow#select_amount_of_seats'
  put 'order_tickets_workflow/receive_selected_amount_of_seats', to: 'order_tickets_workflow#receive_selected_amount_of_seats'
  get 'order_tickets_workflow/select_extras', to: 'order_tickets_workflow#select_extras'
  put 'order_tickets_workflow/receive_selected_extras', to: 'order_tickets_workflow#receive_selected_extras'
  get 'order_tickets_workflow/provide_customer_data', to: 'order_tickets_workflow#provide_customer_data'
  post 'order_tickets_workflow/receive_customer_data', to: 'order_tickets_workflow#receive_customer_data'
  get 'order_tickets_workflow/show_summary', to: 'order_tickets_workflow#show_summary'
  get 'order_tickets_workflow/receive_confirmation', to: 'order_tickets_workflow#receive_confirmation'
  get 'order_tickets_workflow/show_bank_data', to: 'order_tickets_workflow#show_bank_data'

  # Buy gift card workflow
  get 'gutschein', to: 'order_gift_card_workflow#start'
  get 'gutscheine', to: 'order_gift_card_workflow#start'
  get 'order_gift_card_workflow/start', to: 'order_gift_card_workflow#start'
  get 'order_gift_card_workflow/instructions', to: 'order_gift_card_workflow#instructions'
  get 'order_gift_card_workflow/enter_gift_card_number', to: 'order_gift_card_workflow#enter_gift_card_number'
  post 'order_gift_card_workflow/receive_gift_card_number', to: 'order_gift_card_workflow#receive_gift_card_number'
  get 'order_gift_card_workflow/select_gift_card_product', to: 'order_gift_card_workflow#select_gift_card_product'
  get 'order_gift_card_workflow/receive_gift_card_product', to: 'order_gift_card_workflow#receive_gift_card_product'
  get 'order_gift_card_workflow/provide_customer_data', to: 'order_gift_card_workflow#provide_customer_data'
  post 'order_gift_card_workflow/receive_customer_data', to: 'order_gift_card_workflow#receive_customer_data'
  get 'order_gift_card_workflow/show_summary', to: 'order_gift_card_workflow#show_summary'
  get 'order_gift_card_workflow/receive_confirmation', to: 'order_gift_card_workflow#receive_confirmation'
  get 'order_gift_card_workflow/select_payment_method', to: 'order_gift_card_workflow#select_payment_method'
  get 'order_gift_card_workflow/receive_payment_method', to: 'order_gift_card_workflow#receive_payment_method'
  get 'order_gift_card_workflow/show_bank_data', to: 'order_gift_card_workflow#show_bank_data'
  get 'order_gift_card_workflow/paypal_return', to: 'order_gift_card_workflow#paypal_return', as: :paypal_return

  # Back end
  get 'back_end/overview', to: 'back_end#overview'

  match 'back_end/overview' => 'back_end#overview', :as => :overview

  # Orders
  get 'orders/send_confirmation_mail', to: 'orders#send_confirmation_mail'
  get 'orders/send_gift_card_activation_mail', to: 'orders#send_gift_card_activation_mail'

  # Payment notification
  match 'payment_notification/create', to: 'payment_notificatons#create', as: :receive_payment_notification_path




  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :users
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :city, :email, :first_name, :last_name, :salutation, :street_name, :street_number, :zip_code
  validates_presence_of :city, :email, :first_name, :last_name, :salutation, :street_name, :street_number, :zip_code, message: "Bitte f&uuml;llen Sie dieses Feld aus."
  validates_format_of :email, :with => /(^$|^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$)/i, :message => "Bitte geben Sie eine g&uuml;ltige E-Mail-Adresse ein."
  has_many :orders

  def name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :salutation %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :street_name %>
  <%= f.input :street_number %>
  <%= f.input :zip_code %>
  <%= f.input :city %>
  <%= f.input :email %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:salutation) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:street_name) %></th>
      <th><%= model_class.human_attribute_name(:street_number) %></th>
      <th><%= model_class.human_attribute_name(:zip_code) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, customer_path(customer) %></td>
        <td><%= customer.salutation %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.street_name %></td>
        <td><%= customer.street_number %></td>
        <td><%= customer.zip_code %></td>
        <td><%= customer.city %></td>
        <td><%= customer.email %></td>
        <td><%=l customer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:salutation) %>:</strong></dt>
  <dd><%= @customer.salutation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @customer.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @customer.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:street_name) %>:</strong></dt>
  <dd><%= @customer.street_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:street_number) %>:</strong></dt>
  <dd><%= @customer.street_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zip_code) %>:</strong></dt>
  <dd><%= @customer.zip_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @customer.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @customer.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>