config/routes.rb
SesusoEms::Application.routes.draw do
  #resources :categories
  #resources :order_items
  #resources :products
  #resources :orders
  #resources :customers

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => 'home#index'

  #get ':controller/:action'

  # Order Ticket Workflow
  get 'order_tickets_workflow/start', to: 'order_tickets_workflow#start'
  get 'order_tickets_workflow/select_table', to: 'order_tickets_workflow#select_table'
  get 'order_tickets_workflow/get_ball_tables', to: 'order_tickets_workflow#get_ball_tables'
  get 'order_tickets_workflow/receive_selected_table', to: 'order_tickets_workflow#receive_selected_table'
  get 'order_tickets_workflow/select_amount_of_seats', to: 'order_tickets_workflow#select_amount_of_seats'
  put 'order_tickets_workflow/receive_selected_amount_of_seats', to: 'order_tickets_workflow#receive_selected_amount_of_seats'
  get 'order_tickets_workflow/select_extras', to: 'order_tickets_workflow#select_extras'
  put 'order_tickets_workflow/receive_selected_extras', to: 'order_tickets_workflow#receive_selected_extras'
  get 'order_tickets_workflow/provide_customer_data', to: 'order_tickets_workflow#provide_customer_data'
  post 'order_tickets_workflow/receive_customer_data', to: 'order_tickets_workflow#receive_customer_data'
  get 'order_tickets_workflow/show_summary', to: 'order_tickets_workflow#show_summary'
  get 'order_tickets_workflow/receive_confirmation', to: 'order_tickets_workflow#receive_confirmation'
  get 'order_tickets_workflow/show_bank_data', to: 'order_tickets_workflow#show_bank_data'

  # Buy gift card workflow
  get 'gutschein', to: 'order_gift_card_workflow#start'
  get 'gutscheine', to: 'order_gift_card_workflow#start'
  get 'order_gift_card_workflow/start', to: 'order_gift_card_workflow#start'
  get 'order_gift_card_workflow/instructions', to: 'order_gift_card_workflow#instructions'
  get 'order_gift_card_workflow/enter_gift_card_number', to: 'order_gift_card_workflow#enter_gift_card_number'
  post 'order_gift_card_workflow/receive_gift_card_number', to: 'order_gift_card_workflow#receive_gift_card_number'
  get 'order_gift_card_workflow/select_gift_card_product', to: 'order_gift_card_workflow#select_gift_card_product'
  get 'order_gift_card_workflow/receive_gift_card_product', to: 'order_gift_card_workflow#receive_gift_card_product'
  get 'order_gift_card_workflow/provide_customer_data', to: 'order_gift_card_workflow#provide_customer_data'
  post 'order_gift_card_workflow/receive_customer_data', to: 'order_gift_card_workflow#receive_customer_data'
  get 'order_gift_card_workflow/show_summary', to: 'order_gift_card_workflow#show_summary'
  get 'order_gift_card_workflow/receive_confirmation', to: 'order_gift_card_workflow#receive_confirmation'
  get 'order_gift_card_workflow/select_payment_method', to: 'order_gift_card_workflow#select_payment_method'
  get 'order_gift_card_workflow/receive_payment_method', to: 'order_gift_card_workflow#receive_payment_method'
  get 'order_gift_card_workflow/show_bank_data', to: 'order_gift_card_workflow#show_bank_data'
  get 'order_gift_card_workflow/paypal_return', to: 'order_gift_card_workflow#paypal_return', as: :paypal_return

  # Back end
  get 'back_end/overview', to: 'back_end#overview'

  match 'back_end/overview' => 'back_end#overview', :as => :overview

  # Orders
  get 'orders/send_confirmation_mail', to: 'orders#send_confirmation_mail'
  get 'orders/send_gift_card_activation_mail', to: 'orders#send_gift_card_activation_mail'

  # Payment notification
  match 'payment_notification/create', to: 'payment_notificatons#create', as: :receive_payment_notification_path




  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :users
end

app/models/product.rb
class Product < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper

  attr_accessible :caption, :category_id, :number, :price; :quantity

  has_many :order_items

  def get_price()
    number_to_currency(self.price, unit: "&euro;", separator: ",", delimiter: "", format: "%n %u").gsub(' ','&nbsp;').html_safe
  end

  def truncate_float_if_whole_number(number)
    if number.modulo(1) == 0
      number = number.to_int
    end
    return number
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :number %>
  <%= f.input :caption %>
  <%= f.input :price %>
  <%= f.input :category_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:caption) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.number %></td>
        <td><%= product.caption %></td>
        <td><%= product.price %></td>
        <td><%= product.category_id %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @product.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:caption) %>:</strong></dt>
  <dd><%= @product.caption %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @product.category_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>